apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: netlinkie/petclinic:latest
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: petclinic
  ports:
  - port: 5000
    targetPort: 5000
